[workspace]
members = ["crates/*"]

[package]
name = "snowberry"
version = "0.1.0"
edition = "2021"

[dependencies]
snowberry_core = { path = "crates/snowberry_core" }
snowberry_event = { path = "crates/snowberry_event" }
