[package]
name = "snowberry_winit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snowberry_core = { path = "../snowberry_core" }

slotmap = "1.0.7"
winit = "0.30.0"
